# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/CLI.ipynb.

# %% auto 0
__all__ = ['version', 'gen']

# %% ../nbs/CLI.ipynb 2
from typing import *
from pathlib import Path
import importlib

import typer

from .docstring_generator import add_docstring_to_source

# %% ../nbs/CLI.ipynb 5
_app = typer.Typer()


@_app.command(help="Print the version of docstring_gen.")
def version():
    """version()

    Print the version of docstring_gen.

    Args:
        None

    Returns:
        None

    Raises:
        None


    Note: The above docstring is autogenerated by docstring-gen library!
    """
    typer.echo(f'docstring_gen {importlib.import_module("docstring_gen").__version__}')


@_app.command(
    help="This command reads a Jupyter notebook or Python file, or a directory containing these files, and adds docstrings to classes and methods that do not have them. It can be used to add missing docstrings to your codebase.",
)
def gen(
    path: str = typer.Option(
        ...,
        help="The path to the Jupyter notebook or Python file, or a directory containing these files",
    ),
    prompt: Optional[str] = typer.Option(
        None,
        help="Text that will be given as input to the GPT-3 model to generate the docstring. If no text is provided, the docstring will be generated according to the Google Python Style Guide.",
    ),
    include_auto_gen_txt: bool = typer.Option(
        True,
        help="If set to true, a note indicating that the docstring was autogenerated will be added to the end of the docstring.",
    ),
    model: str = typer.Option(
        "code-davinci-002",
        help="The name of the GPT-3 model to use for docstring generation.",
    ),
    temperature: int = typer.Option(
        0, help="The temperature parameter for the GPT-3 model."
    ),
    max_tokens: int = typer.Option(
        250, help="The maximum number of tokens to generate in the docstring."
    ),
    top_p: float = typer.Option(1.0, help="The top-p parameter for the GPT-3 model."),
    frequency_penalty: float = typer.Option(
        0.0, help="The frequency penalty parameter for the GPT-3 model."
    ),
    presence_penalty: float = typer.Option(
        0.0, help="The presence penalty parameter for the GPT-3 model."
    ),
    stop: List[str] = typer.Option(
        ["#", '"""'],
        help="A list of strings that, if encountered in the generated docstring, will cause generation to stop.",
    ),
):
    """Generate docstrings for Python source code using the GPT-3 model.

        :param path: The path to the Jupyter notebook or Python file, or a directory containing these files
        :type path: str
        :param prompt: Text that will be given as input to the GPT-3 model to generate the docstring. If no text is provided, the docstring will be generated according to the Google Python Style Guide.
        :type prompt: Optional[str]
        :param include_auto_gen_txt: If set to true, a note indicating that the docstring was autogenerated will be added to the end of the docstring.
        :type include_auto_gen_txt: bool
        :param model: The name of the GPT-3 model to use for docstring generation.
        :type model: str
        :param temperature: The temperature parameter for the GPT-3 model.
        :type temperature: int
        :param max_tokens: The maximum number of tokens to generate in the docstring.
        :type max_tokens: int
    :param top_p: The top-p parameter for the GPT

        Note: The above docstring is autogenerated by docstring-gen library!
    """
    try:
        add_docstring_to_source(
            path=path,
            prompt=prompt,
            include_auto_gen_txt=include_auto_gen_txt,
            model=model,
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p,
            frequency_penalty=frequency_penalty,
            presence_penalty=presence_penalty,
            stop=stop,
        )
    except Exception as e:
        typer.secho(e, err=True, fg=typer.colors.RED)
        raise typer.Exit(1)
